version: '2'

services:
  talker:
    build:
      context: .
      dockerfile: Dockerfile.demo
    command: ros2 run demo_nodes_cpp talker

  listener:
    build:
      context: .
      dockerfile: Dockerfile.demo
    command: ros2 run demo_nodes_py listener

  web_bridge:
    build:
      context: .
      dockerfile: Dockerfile.ros_bridge
    ports:
      - 9090:9090
