version: '2'
services:
  cprt_web:
    container_name: cprt_web
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["/bin/bash", "-c", "npm install --silent && react-scripts@3.4.1 -g --silent && npm start"]
  maptile_server:
    image: nginx
    ports:
      - 3001:80
    volumes:
      - ./tiles:/tiles
      - ./nginx/nginx_only_tiles.conf:/etc/nginx/conf.d/default.conf
