version: '2'
services:
  cprt_web:
    container_name: cprt_web
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  maptile_server:
    image: nginx
    ports:
      - 3001:80
    volumes:
      - ./tiles:/tiles
      - ./nginx/nginx_only_tiles.conf:/etc/nginx/conf.d/default.conf
